//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolgova
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsInProducts
    {
        public int ID { get; set; }
        public Nullable<int> Material { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Material Material1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
