//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolgova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.MaterialsInProducts = new HashSet<MaterialsInProducts>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> MaterialType { get; set; }
    
        public virtual MaterialType MaterialType1 { get; set; }
        public virtual ICollection<MaterialsInProducts> MaterialsInProducts { get; set; }
    }
}
