//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolgova
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Task_1_DolgovaEntities : DbContext
    {
        public Task_1_DolgovaEntities()
            : base("name=Task_1_DolgovaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material> Material { get; set; }
        public DbSet<MaterialsInProducts> MaterialsInProducts { get; set; }
        public DbSet<MaterialType> MaterialType { get; set; }
        public DbSet<Partner> Partner { get; set; }
        public DbSet<PartnerProducts> PartnerProducts { get; set; }
        public DbSet<PartnerType> PartnerType { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductsInApplication> ProductsInApplication { get; set; }
        public DbSet<ProductType> ProductType { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
