//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolgova
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProducts
    {
        public PartnerProducts()
        {
            this.ProductsInApplication = new HashSet<ProductsInApplication>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Partner { get; set; }
        public Nullable<int> QuantityOfProducts { get; set; }
    
        public virtual Partner Partner1 { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual ICollection<ProductsInApplication> ProductsInApplication { get; set; }
    }
}
