//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolgova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.MaterialsInProducts = new HashSet<MaterialsInProducts>();
            this.PartnerProducts = new HashSet<PartnerProducts>();
            this.ProductsInApplication = new HashSet<ProductsInApplication>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductType { get; set; }
        public string Name { get; set; }
        public Nullable<int> Item { get; set; }
        public Nullable<decimal> MinimumPriceForPartner { get; set; }
    
        public virtual ICollection<MaterialsInProducts> MaterialsInProducts { get; set; }
        public virtual ICollection<PartnerProducts> PartnerProducts { get; set; }
        public virtual ProductType ProductType1 { get; set; }
        public virtual ICollection<ProductsInApplication> ProductsInApplication { get; set; }
    }
}
