//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dolgova
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsInApplication
    {
        public int ID { get; set; }
        public Nullable<int> Bid { get; set; }
        public Nullable<int> Products { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual PartnerProducts PartnerProducts { get; set; }
        public virtual Product Product { get; set; }
    }
}
